# DBTokenizer Demo

This notebook demonstrates the DBTokenizer on synthetic clinical data for two patients.

Data classes:
- demographic: birth date
- lab: hemoglobin, glucose, creatinine
- vital: heart rate, blood pressure, SpO2
- medication: compound, route, frequency, units as text; dose as numeric
- flowsheet: categorical observations (O2 device, diet, fall risk)
- admission / discharge: hospital stay boundaries

We run two configurations:
1. BPE + Discrete + Factored: numeric values are binned into discrete tokens, placed as separate tokens after the text token
2. BPE + Continuous + Fused: numeric values are transformed using a fitted distribution and paired in a parallel float array; concept-mode text+level tokens are fused into single compound tokens

In [ ]:
import polars as pl
import numpy as np
from dbtoken import DBTokenizer

## Load Demo Data

In [ ]:
df = pl.read_csv(
    "data/demo.csv",
    try_parse_dates=True,
    null_values=[""],
)
print(f"Loaded {df.height} rows for {df['id'].n_unique()} patients")
print(f"Classes: {sorted(df['class'].unique().to_list())}")
df.head(20)

## Input schema and token IDs

The supplied data is synthetic. Each row is an event with `id` (integer patient
identifier), `time` (datetime), `class` (event family, string), `text_value`
(nullable string), and `numeric_value` (nullable float, in the measurement's
original units). Sort histories by patient and time. `class` is the field called
`item` in earlier manuscript wording; use `class` consistently. If an older input
has an `item` column, rename it explicitly with `df.rename({"item": "class"})`.
Birth-date rows configure age metadata and are consumed during encoding.

`ids[i]` is a learned vocabulary ID, not a row number or clinical code.
The position printed in brackets is the sequence offset; the explicit `id=`
field below is the actual token ID. Inspect `tok.vocab` for special/concept IDs
and `tok.decode(ids)` for readable pieces, including BPE IDs. IDs are specific
to the trained tokenizer and must be used with its saved vocabulary.
In discrete mode `vals is None`; numerics appear as Q-bin or L-level tokens.
In continuous mode `vals[i]` aligns with `ids[i]`, and NaN means no continuous
payload. The transformation depends on the fitted distribution; values are not
universally z-scores. Fused continuous measurements attach floats to concept
positions; factored measurements use a NUM marker. BPE numerics use factored
placement even when fused placement is requested.

## Configuration 1: BPE + Discrete + Factored

This is the simplest BPE configuration:
- text_mode_default="auto": classes with many unique text values (like medication) get BPE; low-cardinality classes (lab, vital, flowsheet) get concept tokens
- num_type="discrete": numeric values are quantile-binned into `<|Q0|>` … `<|Q{n}|>` tokens (or `<|L0|>` … for ≤10 distinct values)
- num_seq="factored": numeric tokens are emitted as separate tokens after the text token

In [ ]:
tok1 = DBTokenizer(
    text_mode_default="auto",
    text_mode_threshold=4,
    num_type="discrete",
    num_seq="factored",
    n_bins=5,
    final_vocab_size=1024,
    state_transitions={
        "inpatient": ["admission"],
        "default": ["discharge"],
    },
    milestone_per_state={"inpatient": "8hr", "default": "week"},
)
tok1.train(df)

In [ ]:
print("Resolved text modes per class:")
for cls, mode in sorted(tok1.class_text_modes.items()):
    print(f"  {cls:20s} -> {mode}")

In [ ]:
ids1, vals1 = tok1.encode(df)
print(f"Token count: {len(ids1)}")
print(f"vals is None (discrete mode): {vals1 is None}")
print()

# Decode back to human-readable tokens
decoded1 = tok1.decode(ids1)
print("First 60 tokens:")
for i, t in enumerate(decoded1[:60]):
    print(f"  [{i:3d}] id={ids1[i]:5d} {t}")

In [ ]:
# Debug view: see per-row token breakdown
dbg1 = tok1.encode_debug(df)
print("\nDebug view of first 10 rows:")
dbg1.head(10)

# Configuration 2: BPE + Continuous + Fused

This configuration demonstrates:
- num_type="continuous": numeric values are transformed using a fitted distribution, stored in a parallel `vals` array
- num_seq="fused": for concept-mode text groups, scaled floats attach to concept tokens; low-cardinality measurements use compound L-level tokens (e.g. `hemoglobin::L4`)

### Important: Concept Overrides for Fused Numerics

Fused mode only works with concept text tokens (not BPE). For classes that have true numeric measurements you want fused with levels, you must ensure they use concept mode.

Since our lab and vital classes have low cardinality, `auto` already assigns them concept mode. But if any class were incorrectly assigned BPE, you'd override it:
text_mode_overrides={"lab": "concept", "vital": "concept"}

BPE classes automatically fall back to factored numeric placement (with a warning).

In [ ]:
tok2 = DBTokenizer(
    text_mode_default="auto",
    text_mode_threshold=4,
    # Explicitly ensure numeric-bearing classes use concept mode for fusion
    text_mode_overrides={
        "lab": "concept",
        "vital": "concept",
        "flowsheet": "concept",
    },
    num_type="continuous",
    num_seq="fused",
    n_bins=5,
    final_vocab_size=1024,
    state_transitions={
        "inpatient": ["admission"],
        "default": ["discharge"],
    },
    milestone_per_state={"inpatient": "8hr", "default": "week"},
)
tok2.train(df)

In [ ]:
print("Resolved text modes per class:")
for cls, mode in sorted(tok2.class_text_modes.items()):
    print(f"  {cls:20s} -> {mode}")

print()
print("Numeric parameter types:")
for key, params in sorted(tok2.numeric_params.items(), key=str):
    cls, tv = key
    print(f"  ({cls}, {tv}): {params['type']}")

In [ ]:
ids2, vals2 = tok2.encode(df)
print(f"Token count: {len(ids2)}")
print(f"vals length:  {len(vals2)}")
print()

# Show tokens alongside their continuous values
decoded2 = tok2.decode(ids2)
print("First 60 token-value pairs:")
for i, (t, v) in enumerate(zip(decoded2[:60], vals2[:60])):
    v_str = f"{v:8.3f}" if not np.isnan(v) else "     NaN"
    print(f"  [{i:3d}] id={ids2[i]:5d} {v_str}  {t}")

In [ ]:
# Debug view: fused tokens
dbg2 = tok2.encode_debug(df)
dbg2

## Comparison

Let's compare the two configurations side by side.

In [ ]:
print(f"Configuration 1 (BPE + Discrete + Factored):")
print(f"  Total tokens: {len(ids1)}")
print(f"  Vocab size:   {tok1.final_vocab_size}")
print(f"  vals array:   {'None' if vals1 is None else len(vals1)}")
print()
print(f"Configuration 2 (BPE + Continuous + Fused):")
print(f"  Total tokens: {len(ids2)}")
print(f"  Vocab size:   {tok2.final_vocab_size}")
print(f"  vals array:   {len(vals2)}")
print()
print(f"These two configurations differ in sequence length by "
      f"{len(ids1) - len(ids2)} tokens ({(1 - len(ids2)/len(ids1))*100:.1f}%)")

## Save & Load Round-Trip

In [ ]:
import tempfile, os

with tempfile.TemporaryDirectory() as tmpdir:
    path = os.path.join(tmpdir, "demo_tokenizer")
    tok2.save(path)
    tok2_loaded = DBTokenizer.load(path)

    ids2_rt, vals2_rt = tok2_loaded.encode(df)
    assert ids2 == ids2_rt, "Token ID mismatch after round-trip!"
    assert len(vals2) == len(vals2_rt), "Vals length mismatch!"
    print("Save/load round-trip: PASSED ✓")

In [ ]:
# now we will turn the token stream back into a dataframe and see how it compares to the original

df_decoded = tok2.decode_to_dataframe(ids2, vals2)
print("Decoded dataframe head:")
print(df_decoded.head(10))
print("\nOriginal dataframe head:")
print(df.head(10))

## Plain Concept vs. Split Concept vs. BPE Tokenization

The configurations above remain unchanged. This isolated example contrasts one-token concept values, prescribed per-class splitting, and learned BPE pieces. Medication values use the literal delimiter `", "` (comma followed by a space), while vital values use `"_"`.

In [ ]:
# Select one representative row from each class so the contrast is easy to see.
split_examples = pl.concat([
    df.filter(pl.col("class") == "vital").head(1),
    df.filter(pl.col("class") == "medication").head(1),
]).sort(["id", "time", "class"])
split_examples.select(["class", "text_value", "numeric_value"])

In [ ]:
plain_concept_tok = DBTokenizer(
    text_mode_default="concept",
    num_type="discrete",
    num_seq="factored",
)
split_concept_tok = DBTokenizer(
    text_mode_default="concept",
    concept_splitters={
        "medication": ", ",
        "vital": "_",
    },
    num_type="discrete",
    num_seq="factored",
)
bpe_tok = DBTokenizer(
    text_mode_default="bpe",
    num_type="discrete",
    num_seq="factored",
    final_vocab_size=510,
)

plain_concept_tok.train(split_examples)
split_concept_tok.train(split_examples)
bpe_tok.train(split_examples)

In [ ]:
plain_debug = plain_concept_tok.encode_debug(split_examples)
split_debug = split_concept_tok.encode_debug(split_examples)
bpe_debug = bpe_tok.encode_debug(split_examples)

# replace double pipe with quote comma quote. no surrouting spaces on the tokens

# print original data rows
print(split_examples)

print("Demonstration of concept splitting using \"_\" for vitals and \", \" for meds as the splitters")

for row, plain_tokens, split_tokens, bpe_tokens in zip(
    split_examples.iter_rows(named=True),
    plain_debug["tokens"].to_list(),
    split_debug["tokens"].to_list(),
    bpe_debug["tokens"].to_list(),
):
    print(f"{row['class'].upper()}: {row['text_value']}")
    print("  plain concept:")
    print("   " + "\", \"".join(plain_tokens))
    print("  split concept:")
    print("   " + "\", \"".join(split_tokens))
    print("  BPE:")
    print("   " + "\", \"".join(bpe_tokens))
    print()

## MEDS-Style Hierarchical Codes

MEDS-style codes often carry an explicit hierarchy. Here each code uses a literal double backslash (`\\`) between levels, so the tokenizer can preserve those prescribed semantic boundaries instead of learning them from text.

In [ ]:
from datetime import datetime, timedelta

meds_examples = pl.DataFrame(
    [
        {
            "id": 1,
            "time": datetime(2024, 1, 1),
            "class": "meds_code",
            "text_value": r"LAB\\LOINC\\2345-7",
            "numeric_value": None,
        },
        {
            "id": 1,
            "time": datetime(2024, 1, 1) + timedelta(minutes=1),
            "class": "meds_code",
            "text_value": r"DIAGNOSIS\\ICD10CM\\E11.9",
            "numeric_value": None,
        },
    ],
    schema_overrides={"numeric_value": pl.Float64},
)

meds_split_tok = DBTokenizer(
    text_mode_default="auto",
    concept_splitters={"meds_code": r"\\"},
    num_type="discrete",
    num_seq="factored",
)
meds_split_tok.train(meds_examples)
meds_debug = meds_split_tok.encode_debug(meds_examples)

for code, tokens in zip(
    meds_debug["text_value"].to_list(),
    meds_debug["tokens"].to_list(),
):
    pieces = [token for token in tokens if not token.startswith("<|")]
    print(f"MEDS code: {code!r}")
    print(f"  concept pieces: {pieces}")

meds_ids, meds_vals = meds_split_tok.encode(meds_examples)
meds_reconstructed = meds_split_tok.decode_to_dataframe(
    meds_ids, meds_vals, reference_time=datetime(2024, 1, 1)
)
assert meds_reconstructed["text_value"].to_list() == meds_examples["text_value"].to_list()
print("Exact MEDS code round-trip: PASSED")

## Converting a MEDS Table

DBToken uses an opinionated version of MEDS. The MEDS `code` column is split at its first `//`:
- **`class`**: what kind of event this is (`lab`, `vital`, `medication`)
- **`text_value`**: everything else that identifies the concept (`hemoglobin`, `metformin, oral, BID, mg`)

Keeping `class` separate lets DBToken choose a tokenizer per class: one token per value for small vocabularies, or BPE for free text. BPE then runs on `text_value` only, so merges never swallow the event type.

### 1. A conventional MEDS table (toy data, one patient)

In [23]:
from datetime import datetime

pl.Config.set_fmt_str_lengths(100)

hgb = [13.2, 12.8, 11.9, 14.1, 13.5, 12.2, 10.8, 13.9, 12.6, 11.4, 14.5, 13.0]
rows = [(1, datetime(1958, 3, 15), "MEDS_BIRTH", None)]
for i, v in enumerate(hgb):  # 12 days of labs/meds so bins and BPE merges can be fit
    t = datetime(2024, 1, 2 + i, 8)
    rows += [(1, t, "LAB//hemoglobin", v),
             (1, t, "LAB//glucose", 90.0 + 3 * i),
             (1, t, "VITAL//heart_rate", 70.0 + i)]
    rows += [(1, t.replace(hour=9), "MEDICATION//metformin, oral, BID, mg", 500.0),
             (1, t.replace(hour=9), "MEDICATION//lisinopril, oral, daily, mg", 10.0),
             (1, t.replace(hour=21), "MEDICATION//atorvastatin, oral, nightly, mg", 40.0)]

meds_table = pl.DataFrame(rows, schema=["subject_id", "time", "code", "numeric_value"], orient="row").sort("time")
meds_table.head(6)

shape: (6, 4)
┌────────────┬─────────────────────┬─────────────────────────────────────────┬───────────────┐
│ subject_id ┆ time                ┆ code                                    ┆ numeric_value │
│ ---        ┆ ---                 ┆ ---                                     ┆ ---           │
│ i64        ┆ datetime[μs]        ┆ str                                     ┆ f64           │
╞════════════╪═════════════════════╪═════════════════════════════════════════╪═══════════════╡
│ 1          ┆ 1958-03-15 00:00:00 ┆ MEDS_BIRTH                              ┆ null          │
│ 1          ┆ 2024-01-02 08:00:00 ┆ LAB//hemoglobin                         ┆ 13.2          │
│ 1          ┆ 2024-01-02 08:00:00 ┆ LAB//glucose                            ┆ 90.0          │
│ 1          ┆ 2024-01-02 08:00:00 ┆ VITAL//heart_rate                       ┆ 70.0          │
│ 1          ┆ 2024-01-02 09:00:00 ┆ MEDICATION//metformin, oral, BID, mg    ┆ 500.0         │
│ 1          ┆ 2024-01-02 09:00:00 ┆ MEDICATION//lisinopril, oral, daily, mg ┆ 10.0          │
└────────────┴─────────────────────┴─────────────────────────────────────────┴───────────────┘

### 2. Convert: split `code` → (`class`, `text_value`)

The only preprocessing step. `MEDS_BIRTH` has no `//`, so it is remapped to the birth-date row DBToken expects (`demographic`, `birth_date`); this is what produces the age token.

In [24]:
def meds_to_dbtoken(meds: pl.DataFrame) -> pl.DataFrame:
    parts = pl.col("code").str.splitn("//", 2)
    birth = pl.col("code") == "MEDS_BIRTH"
    return (
        meds.rename({"subject_id": "id"})
        .with_columns(
            pl.when(birth).then(pl.lit("demographic"))
              .otherwise(parts.struct.field("field_0").str.to_lowercase()).alias("class"),
            pl.when(birth).then(pl.lit("birth_date"))
              .otherwise(parts.struct.field("field_1")).alias("text_value"),
        )
        .select("id", "time", "class", "text_value", pl.col("numeric_value").cast(pl.Float64))
    )

meds_df = meds_to_dbtoken(meds_table)
pl.concat([meds_table.select("code"), meds_df.select("class", "text_value", "numeric_value")], how="horizontal").head(6)

shape: (6, 4)
┌──────────────────────────────────────┬─────────────┬─────────────────────────────┬───────────────┐
│ code                                 ┆ class       ┆ text_value                  ┆ numeric_value │
│ ---                                  ┆ ---         ┆ ---                         ┆ ---           │
│ str                                  ┆ str         ┆ str                         ┆ f64           │
╞══════════════════════════════════════╪═════════════╪═════════════════════════════╪═══════════════╡
│ MEDS_BIRTH                           ┆ demographic ┆ birth_date                  ┆ null          │
│ LAB//hemoglobin                      ┆ lab         ┆ hemoglobin                  ┆ 13.2          │
│ LAB//glucose                         ┆ lab         ┆ glucose                     ┆ 90.0          │
│ VITAL//heart_rate                    ┆ vital       ┆ heart_rate                  ┆ 70.0          │
│ MEDICATION//metformin, oral, BID, mg ┆ medication  ┆ metformin, oral, BID, mg    ┆ 500.0         │
│ MEDICATION//lisinopril, oral, daily, ┆ medication  ┆ lisinopril, oral, daily, mg ┆ 10.0          │
│ mg                                   ┆             ┆                             ┆               │
└──────────────────────────────────────┴─────────────┴─────────────────────────────┴───────────────┘

### 3. Tokenize

`lab` and `vital` have few distinct values, so they get concept mode (one token per value). `medication` is forced to BPE here to show free-text handling; with real data, auto mode picks BPE for any class with more than 64 distinct values.

In [25]:
def train_and_preview_tokens(tok):
    tok.train(meds_df)
    out = tok.encode_debug(meds_df).with_columns(pl.col("tokens").list.join("  "))
    return (pl.concat([meds_table.select("code"), out.select("numeric_value", "tokens")], how="horizontal")
              .filter(pl.col("code").is_in(["MEDS_BIRTH", "LAB//hemoglobin", "MEDICATION//metformin, oral, BID, mg"]))
              .head(4))

#### 3a. Default: class token, concept token, value-bin token

In [26]:
train_and_preview_tokens(DBTokenizer(text_mode_overrides={"medication": "bpe"}, final_vocab_size=1000))

Extracting birth dates from data...
  Found birth dates for 1 patients
Resolving per-class text modes...
  2 concept classes, 1 BPE classes, 0 pair-level overrides
Training numeric transforms...
  6 numeric groups: 3 level, 3 bins, 0 scaling
Training time-delta transforms...
  scale '0' time-delta: bins (-)
Building vocabulary...
  BPE vocab size: 531 (232 special/concept, 299 BPE merges)
Training complete.

shape: (4, 3)
┌──────────────────────────────────────┬───────────────┬───────────────────────────────────────────┐
│ code                                 ┆ numeric_value ┆ tokens                                    │
│ ---                                  ┆ ---           ┆ ---                                       │
│ str                                  ┆ f64           ┆ str                                       │
╞══════════════════════════════════════╪═══════════════╪═══════════════════════════════════════════╡
│ MEDS_BIRTH                           ┆ null          ┆ <|sos|>                                   │
│ LAB//hemoglobin                      ┆ 13.2          ┆ <|age_65|>  <|lab|>  hemoglobin  <|Q6|>   │
│ MEDICATION//metformin, oral, BID, mg ┆ 500.0         ┆ <|delta_time_0|>  <|Q0|>  <|medication|>  │
│                                      ┆               ┆ metformin  ,   oral  ,   BID  ,   mg      │
│                                      ┆               ┆ <|L0|>                                    │
│ LAB//hemoglobin                      ┆ 12.8          ┆ <|delta_time_0|>  <|Q1|>  <|lab|>         │
│                                      ┆               ┆ hemoglobin  <|Q4|>                        │
└──────────────────────────────────────┴───────────────┴───────────────────────────────────────────┘

#### 3b. Class fused into concept and numeric bin (`<|lab:hemoglobin|>::Qk`): one token per lab result

The warning is expected: BPE classes (medication) cannot fuse, so they keep a separate value token.

In [27]:
train_and_preview_tokens(DBTokenizer(text_mode_overrides={"medication": "bpe"}, final_vocab_size=1000,
                 fuse_class_to_concept=True, num_seq="fused"))

Extracting birth dates from data...
  Found birth dates for 1 patients
Resolving per-class text modes...
  2 concept classes, 1 BPE classes, 0 pair-level overrides
Training numeric transforms...
  6 numeric groups: 3 level, 3 bins, 0 scaling
Training time-delta transforms...
  scale '0' time-delta: bins (-)
Building vocabulary...
  BPE vocab size: 575 (276 special/concept, 299 BPE merges)
Training complete.

shape: (4, 3)
┌──────────────────────────────────────┬───────────────┬───────────────────────────────────────┐
│ code                                 ┆ numeric_value ┆ tokens                                │
│ ---                                  ┆ ---           ┆ ---                                   │
│ str                                  ┆ f64           ┆ str                                   │
╞══════════════════════════════════════╪═══════════════╪═══════════════════════════════════════╡
│ MEDS_BIRTH                           ┆ null          ┆ <|sos|>                               │
│ LAB//hemoglobin                      ┆ 13.2          ┆ <|age_65|>  <|lab:hemoglobin|>::Q6    │
│ MEDICATION//metformin, oral, BID, mg ┆ 500.0         ┆ <|delta_time_0_Q0|>  <|medication|>   │
│                                      ┆               ┆ metformin  ,   oral  ,   BID  ,   mg  │
│                                      ┆               ┆ <|L0|>                                │
│ LAB//hemoglobin                      ┆ 12.8          ┆ <|delta_time_0_Q1|>                   │
│                                      ┆               ┆ <|lab:hemoglobin|>::Q4                │
└──────────────────────────────────────┴───────────────┴───────────────────────────────────────┘

## End-to-end fitting on a patient split

`data/demo.csv` is included with this repository and is entirely synthetic.
The earlier sections inspect the full fixture. For this fitting example we split
by patient **before** training fresh tokenizers: one patient for training and
one for evaluation. The small fixture demonstrates the API only.
Install the examples' dependencies from this repository with
`python -m pip install -e ".[bpe,metrics]"` and run from the repository root.

Medication and flowsheet text are forced to BPE in this split example to encode
unseen evaluation strings. Concept-mode values require a known vocabulary.

In [ ]:
patient_ids = sorted(df['id'].unique().to_list())
train_df = df.filter(pl.col("id") == patient_ids[0])
eval_df = df.filter(pl.col("id") == patient_ids[1])

## Fit a minimal causal model and evaluate bits per row

All data-loader definitions, model definitions, forward calls, and optimizer
steps are included below; no example helper module is imported.
The models use a small causal GRU and run on CPU. BPE changes the token vocabulary,
not the model interface. Both concept and BPE IDs enter an embedding layer.

- **Discrete:** the loader yields `(Xi, Yi)` int64 tensors of shape `[B, T]`.
  `Yi` contains the next token at each position. `model(Xi)` returns
  `(logits, loss)`; logits have shape `[B, T, V]`. Training passes `Yi` for
  categorical cross-entropy. There is no float input or regression head.
- **Continuous:** the loader yields `(Xi, Xv, Yi, Yv)`. IDs are int64;
  aligned values are float32, with NaN at positions without a float payload.
  `model(Xi, Xv, Yi, Yv)` returns `(logits, loc, scale, loss, token_loss,
  value_loss)` as required by the BPR helper. `loc` and positive `scale` are
  `[B, T]` Gaussian parameters in the tokenizer's transformed numeric space.
  The model consumes numeric values and their presence mask; value loss ignores
  NaN targets. Low-cardinality L-level measurements remain categorical.

Each batch contains one complete patient, so targets never cross patient boundaries
and numeric context is retained for BPR. No padding or window truncation is used.
Only four patients per split are used here to keep the fitting example small.
The tokenizer is fixed before evaluation. The short fit is a usage demonstration;
its scores are not a benchmark of predictive performance.

In [ ]:
import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader
from dbtoken.metrics import bits_per_row

def vocabulary_size(tokenizer):
    """Include BPE IDs, which are not all listed in tokenizer.vocab."""
    return tokenizer.bpe.n_vocab if tokenizer.bpe is not None else max(tokenizer.vocab.values()) + 1

## Discrete: train tokenizer → save tokens → fit model → evaluate

In [ ]:
model_tok_discrete = DBTokenizer(text_mode_default="auto", text_mode_threshold=4,
    text_mode_overrides={"medication": "bpe", "flowsheet": "bpe"},
    num_type="discrete", num_seq="factored", n_bins=5, final_vocab_size=1024)
model_tok_discrete.train(train_df)

## Files on disk and save/load verification

Each representation has its own `artifacts/<mode>/` directory. `tokenizer.json`
contains the constructor settings, resolved text modes, vocabulary, numeric bin
edges/levels or fitted scaling parameters, temporal parameters, and demographic
metadata. BPE configurations also write `tokenizer.bpe` containing the serialized
BPE encoding; retain it alongside the JSON and load artifacts from trusted sources.
These are tokenizer artifacts, not model weights. Never reuse a model with a
differently trained vocabulary.

`train.npz` and `eval.npz` store complete encoded streams: `ids` is int64;
continuous files additionally contain aligned float32 `vals`. Discrete files
omit `vals`. Read with `np.load(..., allow_pickle=False)`. These streams include
patient boundary tokens. The model loaders below encode each patient separately
to avoid predicting across patients and to retain full numeric context.

In [ ]:
from pathlib import Path
artifact_dir = Path("artifacts/discrete_factored")
artifact_dir.mkdir(parents=True, exist_ok=True)
model_tok_discrete.save(str(artifact_dir / "tokenizer"))
for split, frame in [("train", train_df), ("eval", eval_df)]:
    stream_ids, stream_vals = model_tok_discrete.encode(frame)
    arrays = {"ids": np.asarray(stream_ids, dtype=np.int64)}
    if stream_vals is not None:
        arrays["vals"] = np.asarray(stream_vals, dtype=np.float32)
    np.savez_compressed(artifact_dir / f"{split}.npz", **arrays)

restored = DBTokenizer.load(str(artifact_dir / "tokenizer"))
original_ids, original_vals = model_tok_discrete.encode(eval_df)
restored_ids, restored_vals = restored.encode(eval_df)
assert original_ids == restored_ids
if original_vals is not None:
    np.testing.assert_allclose(original_vals, restored_vals, equal_nan=True)
else:
    assert restored_vals is None
with np.load(artifact_dir / "eval.npz", allow_pickle=False) as saved:
    print("Saved arrays:", {key: (saved[key].shape, str(saved[key].dtype)) for key in saved.files})
print("Save/load equality verified. Files:", [p.name for p in sorted(artifact_dir.iterdir())])

### Discrete data loader and model

The loader returns `(Xi, Yi)`. IDs are int64. `Yi` is the next-token target;
the model predicts categorical logits with shape `[B,T,V]`.

In [ ]:
def make_discrete_loader(tokenizer, frame, max_patients=4):
    """Separate complete patients; batches contain int64 (Xi, Yi), [1,T]."""
    if tokenizer.num_type != "discrete":
        raise ValueError("Use a discrete tokenizer with this loader")
    samples = []
    for patient in frame["id"].unique().sort().head(max_patients):
        ids, vals = tokenizer.encode(frame.filter(pl.col("id") == patient))
        assert vals is None
        if len(ids) < 2:
            continue
        ids = torch.tensor(ids, dtype=torch.long)
        # Predict the next token without crossing a patient boundary.
        samples.append((ids[:-1], ids[1:]))
    if not samples:
        raise ValueError("No patient sequences with at least two tokens")
    # Batch size 1 supports different sequence lengths without padding.
    return DataLoader(samples, batch_size=1, shuffle=False)

In [ ]:
class DiscreteModel(nn.Module):
    """Embedding → causal GRU → categorical next-token logits [B,T,V]."""
    def __init__(self, vocab_size, width=24):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, width)
        self.rnn = nn.GRU(width, width, batch_first=True)
        self.head = nn.Linear(width, vocab_size)

    def forward(self, xi, targets=None):
        hidden, _ = self.rnn(self.embedding(xi))
        logits = self.head(hidden)
        loss = None if targets is None else F.cross_entropy(
            logits.reshape(-1, logits.size(-1)), targets.reshape(-1))
        return logits, loss

In [ ]:
torch.manual_seed(7)
discrete_train_loader = make_discrete_loader(model_tok_discrete, train_df, max_patients=4)
discrete_eval_loader = make_discrete_loader(model_tok_discrete, eval_df, max_patients=4)
discrete_model = DiscreteModel(vocabulary_size(model_tok_discrete))
print("Batch tensor shapes:", [tuple(t.shape) for t in next(iter(discrete_train_loader))])
Xi, Yi = next(iter(discrete_train_loader))
print("Xi (input IDs):", Xi[0, :8])
print("Yi (next IDs): ", Yi[0, :8])
logits, loss = discrete_model(Xi, Yi)
print("Next-token logits:", tuple(logits.shape), "initial loss:", loss.item())

### Fit the discrete model

In [ ]:
# Fit this model using its representation-specific input/target tensors.
optimizer = torch.optim.Adam(discrete_model.parameters(), lr=0.003)
discrete_model.train()
for epoch in range(50):
    total_loss = 0.0
    for batch in discrete_train_loader:
        optimizer.zero_grad()
        Xi, Yi = batch
        _, loss = discrete_model(Xi, Yi)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch + 1} mean loss: {total_loss / len(discrete_train_loader):.4f}")

### Evaluate the discrete model with BPR

In [ ]:
# Evaluate the fixed tokenizer and fitted model on held-out histories.
discrete_scores = bits_per_row(
    discrete_model, model_tok_discrete, discrete_eval_loader,
    model_type="discrete", tail_mode="width",
)
print("Discrete BPR results:")
for name, value in discrete_scores.items():
    print(f"  {name}: {value}")
assert discrete_scores["n_rows"] > 0

## Continuous: train tokenizer → save tokens → fit model → evaluate

In [ ]:
model_tok_continuous = DBTokenizer(text_mode_default="auto", text_mode_threshold=4,
    text_mode_overrides={"medication": "bpe", "flowsheet": "bpe"},
    num_type="continuous", num_seq="fused", n_bins=5, final_vocab_size=1024)
model_tok_continuous.train(train_df)

In [ ]:
from pathlib import Path
artifact_dir = Path("artifacts/continuous_fused")
artifact_dir.mkdir(parents=True, exist_ok=True)
model_tok_continuous.save(str(artifact_dir / "tokenizer"))
for split, frame in [("train", train_df), ("eval", eval_df)]:
    stream_ids, stream_vals = model_tok_continuous.encode(frame)
    arrays = {"ids": np.asarray(stream_ids, dtype=np.int64)}
    if stream_vals is not None:
        arrays["vals"] = np.asarray(stream_vals, dtype=np.float32)
    np.savez_compressed(artifact_dir / f"{split}.npz", **arrays)

restored = DBTokenizer.load(str(artifact_dir / "tokenizer"))
original_ids, original_vals = model_tok_continuous.encode(eval_df)
restored_ids, restored_vals = restored.encode(eval_df)
assert original_ids == restored_ids
if original_vals is not None:
    np.testing.assert_allclose(original_vals, restored_vals, equal_nan=True)
else:
    assert restored_vals is None
with np.load(artifact_dir / "eval.npz", allow_pickle=False) as saved:
    print("Saved arrays:", {key: (saved[key].shape, str(saved[key].dtype)) for key in saved.files})
print("Save/load equality verified. Files:", [p.name for p in sorted(artifact_dir.iterdir())])

### Continuous data loader and model

The loader returns `(Xi, Xv, Yi, Yv)`. IDs are int64 and values are float32.
Values stay aligned when shifted into inputs and targets. NaN marks positions
without a float. The model consumes values and missingness, and predicts
categorical logits plus Gaussian location and positive scale `[B,T]`.

In [ ]:
def make_continuous_loader(tokenizer, frame, max_patients=4):
    """Batches contain (Xi, Xv, Yi, Yv), all [1,T]; NaN means no float."""
    if tokenizer.num_type != "continuous":
        raise ValueError("Use a continuous tokenizer with this loader")
    samples = []
    for patient in frame["id"].unique().sort().head(max_patients):
        ids, vals = tokenizer.encode(frame.filter(pl.col("id") == patient))
        assert vals is not None and len(ids) == len(vals)
        if len(ids) < 2:
            continue
        ids = torch.tensor(ids, dtype=torch.long)
        vals = torch.tensor(vals, dtype=torch.float32)
        # Shift IDs and their aligned floats together. Keep NaN payloads:
        # the model handles missing inputs and masks missing value targets.
        samples.append((ids[:-1], vals[:-1], ids[1:], vals[1:]))
    if not samples:
        raise ValueError("No patient sequences with at least two tokens")
    return DataLoader(samples, batch_size=1, shuffle=False)

In [ ]:
class ContinuousModel(nn.Module):
    """Token + value + missingness inputs; categorical and Gaussian outputs.

    Match bits_per_row's six-result forward interface. Gaussian loc/scale
    and value targets are [B,T]; scale must be positive. NaN targets mark
    positions with no continuous payload and are excluded from value loss.
    Discrete L-level tokens remain categorical even in continuous mode.
    """
    def __init__(self, vocab_size, width=24):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, width)
        self.value_embedding = nn.Linear(2, width)
        self.rnn = nn.GRU(width, width, batch_first=True)
        self.token_head = nn.Linear(width, vocab_size)
        self.value_head = nn.Linear(width, 2)

    def forward(self, xi, xv, yi=None, yv=None):
        present = ~torch.isnan(xv)
        features = torch.stack((torch.nan_to_num(xv), present.float()), dim=-1)
        hidden, _ = self.rnn(self.embedding(xi) + self.value_embedding(features))
        logits = self.token_head(hidden)
        loc, raw_scale = self.value_head(hidden).unbind(-1)
        scale = F.softplus(raw_scale) + 1e-4
        loss = token_loss = value_loss = None
        if yi is not None:
            token_loss = F.cross_entropy(logits.reshape(-1, logits.size(-1)), yi.reshape(-1))
            mask = ~torch.isnan(yv)
            # Index first: a NaN must never enter the Gaussian likelihood.
            value_loss = (-torch.distributions.Normal(loc[mask], scale[mask])
                          .log_prob(yv[mask]).mean()) if mask.any() else loc.sum() * 0
            loss = token_loss + value_loss
        return logits, loc, scale, loss, token_loss, value_loss

In [ ]:
torch.manual_seed(7)
continuous_train_loader = make_continuous_loader(model_tok_continuous, train_df, max_patients=4)
continuous_eval_loader = make_continuous_loader(model_tok_continuous, eval_df, max_patients=4)
continuous_model = ContinuousModel(vocabulary_size(model_tok_continuous))
print("Batch tensor shapes:", [tuple(t.shape) for t in next(iter(continuous_train_loader))])
Xi, Xv, Yi, Yv = next(iter(continuous_train_loader))
print("Xi (input IDs):", Xi[0, :8])
print("Xv (input values):", Xv[0, :8])
print("Yi (next IDs):", Yi[0, :8])
print("Yv (next values):", Yv[0, :8])
logits, loc, scale, loss, token_loss, value_loss = continuous_model(Xi, Xv, Yi, Yv)
print("Next-token logits:", tuple(logits.shape), "initial loss:", loss.item())

### Fit the continuous model

In [ ]:
# Fit this model using its representation-specific input/target tensors.
optimizer = torch.optim.Adam(continuous_model.parameters(), lr=0.003)
continuous_model.train()
for epoch in range(50):
    total_loss = 0.0
    for batch in continuous_train_loader:
        optimizer.zero_grad()
        Xi, Xv, Yi, Yv = batch
        _, _, _, loss, _, _ = continuous_model(Xi, Xv, Yi, Yv)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch + 1} mean loss: {total_loss / len(continuous_train_loader):.4f}")

### Evaluate the continuous model with BPR

In [ ]:
# Evaluate the fixed tokenizer and fitted model on held-out histories.
continuous_scores = bits_per_row(
    continuous_model, model_tok_continuous, continuous_eval_loader,
    model_type="continuous", tail_mode="width",
)
print("Continuous BPR results:")
for name, value in continuous_scores.items():
    print(f"  {name}: {value}")
assert continuous_scores["n_rows"] > 0

The returned BPR dictionaries are printed in full above. `bpr` is the
sum of density-adjusted bits divided by the number of represented data rows;
`bpr_raw` omits the density adjustment. `class_bpr`, `text_bpr`, `numeric_bpr`,
`level_bpr`, `fused_bpr`, `time_bpr`, `milestone_bpr`, `age_bpr`, and `eos_bpr`
show the contributions. `n_rows`, `tokens_per_row`, and `tail_mode` describe
what was scored. Birth-date metadata rows do not count as clinical rows.
Lower BPR indicates better likelihood on the same evaluation rows. Comparisons
require identical source rows, units, splits, and tail conventions. Density-based
scores may be negative. `tail_mode="width"` borrows neighboring widths for open
edge bins; `"censored"` instead scores tail events as probability mass.