# DBTokenizer Demo

This notebook demonstrates the DBTokenizer on synthetic clinical data for two patients.

Data classes:
- demographic: birth date
- lab: hemoglobin, glucose, creatinine
- vital: heart rate, blood pressure, SpO2
- medication: compound, route, frequency, units as text; dose as numeric
- flowsheet: categorical observations (O2 device, diet, fall risk)
- admission / discharge: hospital stay boundaries

We run two configurations:
1. BPE + Discrete + Factored: numeric values are binned into discrete tokens, placed as separate tokens after the text token
2. BPE + Continuous + Fused: numeric values are transformed using a fitted distribution and paired in a parallel float array; concept-mode text+level tokens are fused into single compound tokens

In [22]:
import polars as pl
import numpy as np
from dbtoken import DBTokenizer

## Load Demo Data

In [23]:
df = pl.read_csv(
    "data/demo.csv",
    try_parse_dates=True,
    null_values=[""],
)
print(f"Loaded {df.height} rows for {df['id'].n_unique()} patients")
print(f"Classes: {sorted(df['class'].unique().to_list())}")
df.head(20)

Loaded 106 rows for 2 patients
Classes: ['admission', 'demographic', 'discharge', 'flowsheet', 'lab', 'medication', 'vital']

shape: (20, 5)
┌─────┬─────────────────────┬─────────────┬──────────────────────────┬───────────────┐
│ id  ┆ time                ┆ class       ┆ text_value               ┆ numeric_value │
│ --- ┆ ---                 ┆ ---         ┆ ---                      ┆ ---           │
│ i64 ┆ datetime[μs]        ┆ str         ┆ str                      ┆ f64           │
╞═════╪═════════════════════╪═════════════╪══════════════════════════╪═══════════════╡
│ 1   ┆ 1958-03-15 00:00:00 ┆ demographic ┆ birth_date               ┆ null          │
│ 1   ┆ 2024-01-02 08:00:00 ┆ lab         ┆ hemoglobin               ┆ 13.2          │
│ 1   ┆ 2024-01-02 08:00:00 ┆ lab         ┆ glucose                  ┆ 98.0          │
│ 1   ┆ 2024-01-02 08:00:00 ┆ lab         ┆ creatinine               ┆ 0.9           │
│ 1   ┆ 2024-01-02 08:05:00 ┆ vital       ┆ heart_rate               ┆ 78.0          │
│ …   ┆ …                   ┆ …           ┆ …                        ┆ …             │
│ 1   ┆ 2024-01-15 09:30:00 ┆ lab         ┆ creatinine               ┆ 1.0           │
│ 1   ┆ 2024-01-15 09:35:00 ┆ vital       ┆ heart_rate               ┆ 82.0          │
│ 1   ┆ 2024-01-15 09:35:00 ┆ vital       ┆ blood_pressure_systolic  ┆ 132.0         │
│ 1   ┆ 2024-01-15 09:35:00 ┆ vital       ┆ blood_pressure_diastolic ┆ 85.0          │
│ 1   ┆ 2024-01-15 09:35:00 ┆ vital       ┆ spo2                     ┆ 96.0          │
└─────┴─────────────────────┴─────────────┴──────────────────────────┴───────────────┘

## Input schema and token IDs

The supplied data is synthetic. Each row is an event with `id` (integer patient
identifier), `time` (datetime), `class` (event family, string), `text_value`
(nullable string), and `numeric_value` (nullable float, in the measurement's
original units). Sort histories by patient and time. `class` is the field called
`item` in earlier manuscript wording; use `class` consistently. If an older input
has an `item` column, rename it explicitly with `df.rename({"item": "class"})`.
Birth-date rows configure age metadata and are consumed during encoding.

`ids[i]` is a learned vocabulary ID, not a row number or clinical code.
The position printed in brackets is the sequence offset; the explicit `id=`
field below is the actual token ID. Inspect `tok.vocab` for special/concept IDs
and `tok.decode(ids)` for readable pieces, including BPE IDs. IDs are specific
to the trained tokenizer and must be used with its saved vocabulary.
In discrete mode `vals is None`; numerics appear as Q-bin or L-level tokens.
In continuous mode `vals[i]` aligns with `ids[i]`, and NaN means no continuous
payload. The transformation depends on the fitted distribution; values are not
universally z-scores. Fused continuous measurements attach floats to concept
positions; factored measurements use a NUM marker. BPE numerics use factored
placement even when fused placement is requested.

## Configuration 1: BPE + Discrete + Factored

This is the simplest BPE configuration:
- text_mode_default="auto": classes with many unique text values (like medication) get BPE; low-cardinality classes (lab, vital, flowsheet) get concept tokens
- num_type="discrete": numeric values are quantile-binned into `<|Q0|>` … `<|Q{n}|>` tokens (or `<|L0|>` … for ≤10 distinct values)
- num_seq="factored": numeric tokens are emitted as separate tokens after the text token

In [24]:
tok1 = DBTokenizer(
    text_mode_default="auto",
    text_mode_threshold=4,
    num_type="discrete",
    num_seq="factored",
    n_bins=5,
    final_vocab_size=1024,
    state_transitions={
        "inpatient": ["admission"],
        "default": ["discharge"],
    },
    milestone_per_state={"inpatient": "8hr", "default": "week"},
)
tok1.train(df)

Extracting birth dates from data...
  Found birth dates for 2 patients
Resolving per-class text modes...
  4 concept classes, 2 BPE classes, 0 pair-level overrides
Training numeric transforms...
  13 numeric groups: 11 level, 2 bins, 0 scaling
Training time-delta transforms...
  scale '0' time-delta: bins (-)
Building vocabulary...
  BPE vocab size: 617 (236 special/concept, 381 BPE merges)
Training complete.

In [25]:
print("Resolved text modes per class:")
for cls, mode in sorted(tok1.class_text_modes.items()):
    print(f"  {cls:20s} -> {mode}")

Resolved text modes per class:
  admission            -> concept
  discharge            -> concept
  flowsheet            -> bpe
  lab                  -> concept
  medication           -> bpe
  vital                -> concept

In [26]:
ids1, vals1 = tok1.encode(df)
print(f"Token count: {len(ids1)}")
print(f"vals is None (discrete mode): {vals1 is None}")
print()

# Decode back to human-readable tokens
decoded1 = tok1.decode(ids1)
print("First 60 tokens:")
for i, t in enumerate(decoded1[:60]):
    print(f"  [{i:3d}] id={ids1[i]:5d} {t}")

Token count: 530
vals is None (discrete mode): True

First 60 tokens:
  [  0] id=  381 <|sos|>
  [  1] id=  545 <|age_65|>
  [  2] id=  602 <|lab|>
  [  3] id=  613 hemoglobin
  [  4] id=  399 <|L7|>
  [  5] id=  602 <|lab|>
  [  6] id=  608 glucose
  [  7] id=  394 <|L2|>
  [  8] id=  602 <|lab|>
  [  9] id=  612 creatinine
  [ 10] id=  393 <|L1|>
  [ 11] id=  384 <|delta_time_0|>
  [ 12] id=  386 <|Q0|>
  [ 13] id=  403 <|ms_week_1|>
  [ 14] id=  605 <|vital|>
  [ 15] id=  609 heart_rate
  [ 16] id=  387 <|Q1|>
  [ 17] id=  605 <|vital|>
  [ 18] id=  614 blood_pressure_systolic
  [ 19] id=  387 <|Q1|>
  [ 20] id=  605 <|vital|>
  [ 21] id=  615 blood_pressure_diastolic
  [ 22] id=  395 <|L3|>
  [ 23] id=  605 <|vital|>
  [ 24] id=  611 spo2
  [ 25] id=  397 <|L5|>
  [ 26] id=  384 <|delta_time_0|>
  [ 27] id=  386 <|Q0|>
  [ 28] id=  606 <|medication|>
  [ 29] id=  318 lisinopril
  [ 30] id=   44 ,
  [ 31] id=  268  oral
  [ 32] id=   44 ,
  [ 33] id=  287  daily
  [ 34] id=   44 ,
  [ 35] id=  259  mg
  [ 36] id=  392 <|L0|>
  [ 37] id=  606 <|medication|>
  [ 38] id=  360 metformin
  [ 39] id=   44 ,
  [ 40] id=  268  oral
  [ 41] id=   44 ,
  [ 42] id=  279  BID
  [ 43] id=   44 ,
  [ 44] id=  259  mg
  [ 45] id=  392 <|L0|>
  [ 46] id=  384 <|delta_time_0|>
  [ 47] id=  386 <|Q0|>
  [ 48] id=  603 <|flowsheet|>
  [ 49] id=  111 o
  [ 50] id=   50 2
  [ 51] id=  281 _device
  [ 52] id=   58 :
  [ 53] id=  314  room
  [ 54] id=  315 _air
  [ 55] id=  603 <|flowsheet|>
  [ 56] id=  353 diet
  [ 57] id=   58 :
  [ 58] id=  380  regular
  [ 59] id=  603 <|flowsheet|>

In [27]:
# Debug view: see per-row token breakdown
dbg1 = tok1.encode_debug(df)
print("\nDebug view of first 10 rows:")
dbg1.head(10)

Debug view of first 10 rows:

shape: (10, 6)
┌─────┬───────────────┬─────────────┬───────────────────────┬───────────────┬──────────────────────┐
│ id  ┆ time          ┆ class       ┆ text_value            ┆ numeric_value ┆ tokens               │
│ --- ┆ ---           ┆ ---         ┆ ---                   ┆ ---           ┆ ---                  │
│ i64 ┆ datetime[μs]  ┆ str         ┆ str                   ┆ f64           ┆ list[str]            │
╞═════╪═══════════════╪═════════════╪═══════════════════════╪═══════════════╪══════════════════════╡
│ 1   ┆ 1958-03-15    ┆ demographic ┆ birth_date            ┆ null          ┆ ["<|sos|>"]          │
│     ┆ 00:00:00      ┆             ┆                       ┆               ┆                      │
│ 1   ┆ 2024-01-02    ┆ lab         ┆ hemoglobin            ┆ 13.2          ┆ ["<|age_65|>",       │
│     ┆ 08:00:00      ┆             ┆                       ┆               ┆ "<|lab|>", … "<…     │
│ 1   ┆ 2024-01-02    ┆ lab         ┆ glucose               ┆ 98.0          ┆ ["<|lab|>",          │
│     ┆ 08:00:00      ┆             ┆                       ┆               ┆ "glucose", "<|L2|>…  │
│ 1   ┆ 2024-01-02    ┆ lab         ┆ creatinine            ┆ 0.9           ┆ ["<|lab|>",          │
│     ┆ 08:00:00      ┆             ┆                       ┆               ┆ "creatinine", "<|L…  │
│ 1   ┆ 2024-01-02    ┆ vital       ┆ heart_rate            ┆ 78.0          ┆ ["<|delta_time_0|>", │
│     ┆ 08:05:00      ┆             ┆                       ┆               ┆ "<|Q0|>",…           │
│ 1   ┆ 2024-01-02    ┆ vital       ┆ blood_pressure_systol ┆ 128.0         ┆ ["<|vital|>",        │
│     ┆ 08:05:00      ┆             ┆ ic                    ┆               ┆ "blood_pressure_…    │
│ 1   ┆ 2024-01-02    ┆ vital       ┆ blood_pressure_diasto ┆ 82.0          ┆ ["<|vital|>",        │
│     ┆ 08:05:00      ┆             ┆ lic                   ┆               ┆ "blood_pressure_…    │
│ 1   ┆ 2024-01-02    ┆ vital       ┆ spo2                  ┆ 97.0          ┆ ["<|vital|>",        │
│     ┆ 08:05:00      ┆             ┆                       ┆               ┆ "spo2", "<|L5|>"…    │
│ 1   ┆ 2024-01-02    ┆ medication  ┆ lisinopril, oral,     ┆ 10.0          ┆ ["<|delta_time_0|>", │
│     ┆ 08:10:00      ┆             ┆ daily, mg             ┆               ┆ "<|Q0|>",…           │
│ 1   ┆ 2024-01-02    ┆ medication  ┆ metformin, oral, BID, ┆ 500.0         ┆ ["<|medication|>",   │
│     ┆ 08:10:00      ┆             ┆ mg                    ┆               ┆ "metformin"…         │
└─────┴───────────────┴─────────────┴───────────────────────┴───────────────┴──────────────────────┘

# Configuration 2: BPE + Continuous + Fused

This configuration demonstrates:
- num_type="continuous": numeric values are transformed using a fitted distribution, stored in a parallel `vals` array
- num_seq="fused": for concept-mode text groups, scaled floats attach to concept tokens; low-cardinality measurements use compound L-level tokens (e.g. `hemoglobin::L4`)

### Important: Concept Overrides for Fused Numerics

Fused mode only works with concept text tokens (not BPE). For classes that have true numeric measurements you want fused with levels, you must ensure they use concept mode.

Since our lab and vital classes have low cardinality, `auto` already assigns them concept mode. But if any class were incorrectly assigned BPE, you'd override it:
text_mode_overrides={"lab": "concept", "vital": "concept"}

BPE classes automatically fall back to factored numeric placement (with a warning).

In [28]:
tok2 = DBTokenizer(
    text_mode_default="auto",
    text_mode_threshold=4,
    # Explicitly ensure numeric-bearing classes use concept mode for fusion
    text_mode_overrides={
        "lab": "concept",
        "vital": "concept",
        "flowsheet": "concept",
    },
    num_type="continuous",
    num_seq="fused",
    n_bins=5,
    final_vocab_size=1024,
    state_transitions={
        "inpatient": ["admission"],
        "default": ["discharge"],
    },
    milestone_per_state={"inpatient": "8hr", "default": "week"},
)
tok2.train(df)

Extracting birth dates from data...
  Found birth dates for 2 patients
Resolving per-class text modes...
  5 concept classes, 1 BPE classes, 0 pair-level overrides
Training numeric transforms...
  13 numeric groups: 11 level, 0 bins, 2 scaling
Training time-delta transforms...
  scale '0' time-delta: scaling (lognormal)
Building vocabulary...
  BPE vocab size: 615 (285 special/concept, 330 BPE merges)
Training complete.

In [29]:
print("Resolved text modes per class:")
for cls, mode in sorted(tok2.class_text_modes.items()):
    print(f"  {cls:20s} -> {mode}")

print()
print("Numeric parameter types:")
for key, params in sorted(tok2.numeric_params.items(), key=str):
    cls, tv = key
    print(f"  ({cls}, {tv}): {params['type']}")

Resolved text modes per class:
  admission            -> concept
  discharge            -> concept
  flowsheet            -> concept
  lab                  -> concept
  medication           -> bpe
  vital                -> concept

Numeric parameter types:
  (lab, creatinine): level
  (lab, glucose): level
  (lab, hemoglobin): level
  (medication, atorvastatin, oral, daily, mg): level
  (medication, furosemide, IV, BID, mg): level
  (medication, heparin, IV, continuous, units): level
  (medication, lisinopril, oral, daily, mg): level
  (medication, metformin, oral, BID, mg): level
  (medication, vancomycin, IV, q12h, mg): level
  (vital, blood_pressure_diastolic): level
  (vital, blood_pressure_systolic): scaling
  (vital, heart_rate): scaling
  (vital, spo2): level

In [30]:
ids2, vals2 = tok2.encode(df)
print(f"Token count: {len(ids2)}")
print(f"vals length:  {len(vals2)}")
print()

# Show tokens alongside their continuous values
decoded2 = tok2.decode(ids2)
print("First 60 token-value pairs:")
for i, (t, v) in enumerate(zip(decoded2[:60], vals2[:60])):
    v_str = f"{v:8.3f}" if not np.isnan(v) else "     NaN"
    print(f"  [{i:3d}] id={ids2[i]:5d} {v_str}  {t}")

Token count: 374
vals length:  374

First 60 token-value pairs:
  [  0] id=  330      NaN  <|sos|>
  [  1] id=  494      NaN  <|age_65|>
  [  2] id=  555      NaN  <|lab|>
  [  3] id=  581      NaN  hemoglobin::L7
  [  4] id=  555      NaN  <|lab|>
  [  5] id=  585      NaN  glucose::L2
  [  6] id=  555      NaN  <|lab|>
  [  7] id=  610      NaN  creatinine::L1
  [  8] id=  333   -0.996  <|delta_time_0|>
  [  9] id=  352      NaN  <|ms_week_1|>
  [ 10] id=  551      NaN  <|vital|>
  [ 11] id=  559   -0.557  heart_rate
  [ 12] id=  551      NaN  <|vital|>
  [ 13] id=  571   -0.555  blood_pressure_systolic
  [ 14] id=  551      NaN  <|vital|>
  [ 15] id=  603      NaN  blood_pressure_diastolic::L3
  [ 16] id=  551      NaN  <|vital|>
  [ 17] id=  597      NaN  spo2::L5
  [ 18] id=  333   -0.996  <|delta_time_0|>
  [ 19] id=  553      NaN  <|medication|>
  [ 20] id=  291      NaN  lisinopril
  [ 21] id=   44      NaN  ,
  [ 22] id=  265      NaN   oral
  [ 23] id=   44      NaN  ,
  [ 24] id=  272      NaN   daily
  [ 25] id=   44      NaN  ,
  [ 26] id=  258      NaN   mg
  [ 27] id=  341      NaN  <|L0|>
  [ 28] id=  553      NaN  <|medication|>
  [ 29] id=  323      NaN  metformin
  [ 30] id=   44      NaN  ,
  [ 31] id=  265      NaN   oral
  [ 32] id=   44      NaN  ,
  [ 33] id=  268      NaN   BID
  [ 34] id=   44      NaN  ,
  [ 35] id=  258      NaN   mg
  [ 36] id=  341      NaN  <|L0|>
  [ 37] id=  333   -0.996  <|delta_time_0|>
  [ 38] id=  556      NaN  <|flowsheet|>
  [ 39] id=  565      NaN  o2_device: room_air
  [ 40] id=  556      NaN  <|flowsheet|>
  [ 41] id=  564      NaN  diet: regular
  [ 42] id=  556      NaN  <|flowsheet|>
  [ 43] id=  562      NaN  fall_risk: low
  [ 44] id=  333    1.753  <|delta_time_0|>
  [ 45] id=  354      NaN  <|ms_week_3|>
  [ 46] id=  555      NaN  <|lab|>
  [ 47] id=  579      NaN  hemoglobin::L5
  [ 48] id=  555      NaN  <|lab|>
  [ 49] id=  586      NaN  glucose::L3
  [ 50] id=  555      NaN  <|lab|>
  [ 51] id=  611      NaN  creatinine::L2
  [ 52] id=  333   -0.996  <|delta_time_0|>
  [ 53] id=  551      NaN  <|vital|>
  [ 54] id=  559   -0.132  heart_rate
  [ 55] id=  551      NaN  <|vital|>
  [ 56] id=  571   -0.151  blood_pressure_systolic
  [ 57] id=  551      NaN  <|vital|>
  [ 58] id=  605      NaN  blood_pressure_diastolic::L5
  [ 59] id=  551      NaN  <|vital|>

In [31]:
# Debug view: fused tokens
dbg2 = tok2.encode_debug(df)
dbg2

shape: (106, 6)
┌─────┬───────────────┬─────────────┬───────────────────────┬───────────────┬──────────────────────┐
│ id  ┆ time          ┆ class       ┆ text_value            ┆ numeric_value ┆ tokens               │
│ --- ┆ ---           ┆ ---         ┆ ---                   ┆ ---           ┆ ---                  │
│ i64 ┆ datetime[μs]  ┆ str         ┆ str                   ┆ f64           ┆ list[str]            │
╞═════╪═══════════════╪═════════════╪═══════════════════════╪═══════════════╪══════════════════════╡
│ 1   ┆ 1958-03-15    ┆ demographic ┆ birth_date            ┆ null          ┆ ["<|sos|>"]          │
│     ┆ 00:00:00      ┆             ┆                       ┆               ┆                      │
│ 1   ┆ 2024-01-02    ┆ lab         ┆ hemoglobin            ┆ 13.2          ┆ ["<|age_65|>",       │
│     ┆ 08:00:00      ┆             ┆                       ┆               ┆ "<|lab|>", "hem…     │
│ 1   ┆ 2024-01-02    ┆ lab         ┆ glucose               ┆ 98.0          ┆ ["<|lab|>",          │
│     ┆ 08:00:00      ┆             ┆                       ┆               ┆ "glucose::L2"]       │
│ 1   ┆ 2024-01-02    ┆ lab         ┆ creatinine            ┆ 0.9           ┆ ["<|lab|>",          │
│     ┆ 08:00:00      ┆             ┆                       ┆               ┆ "creatinine::L1"]    │
│ 1   ┆ 2024-01-02    ┆ vital       ┆ heart_rate            ┆ 78.0          ┆ ["<|delta_time_0|>(- │
│     ┆ 08:05:00      ┆             ┆                       ┆               ┆ 0.996)", "…          │
│ …   ┆ …             ┆ …           ┆ …                     ┆ …             ┆ …                    │
│ 2   ┆ 2024-03-20    ┆ vital       ┆ blood_pressure_systol ┆ 122.0         ┆ ["<|vital|>",        │
│     ┆ 10:15:00      ┆             ┆ ic                    ┆               ┆ "blood_pressure_…    │
│ 2   ┆ 2024-03-20    ┆ vital       ┆ blood_pressure_diasto ┆ 78.0          ┆ ["<|vital|>",        │
│     ┆ 10:15:00      ┆             ┆ lic                   ┆               ┆ "blood_pressure_…    │
│ 2   ┆ 2024-03-20    ┆ vital       ┆ spo2                  ┆ 98.0          ┆ ["<|vital|>",        │
│     ┆ 10:15:00      ┆             ┆                       ┆               ┆ "spo2::L6"]          │
│ 2   ┆ 2024-03-20    ┆ medication  ┆ atorvastatin, oral,   ┆ 40.0          ┆ ["<|delta_time_0|>(- │
│     ┆ 10:20:00      ┆             ┆ daily, mg             ┆               ┆ 0.996)", "…          │
│ 2   ┆ 2024-03-20    ┆ medication  ┆ lisinopril, oral,     ┆ 10.0          ┆ ["<|medication|>",   │
│     ┆ 10:20:00      ┆             ┆ daily, mg             ┆               ┆ "lisinopril…         │
└─────┴───────────────┴─────────────┴───────────────────────┴───────────────┴──────────────────────┘

## Comparison

Let's compare the two configurations side by side.

In [32]:
print(f"Configuration 1 (BPE + Discrete + Factored):")
print(f"  Total tokens: {len(ids1)}")
print(f"  Vocab size:   {tok1.final_vocab_size}")
print(f"  vals array:   {'None' if vals1 is None else len(vals1)}")
print()
print(f"Configuration 2 (BPE + Continuous + Fused):")
print(f"  Total tokens: {len(ids2)}")
print(f"  Vocab size:   {tok2.final_vocab_size}")
print(f"  vals array:   {len(vals2)}")
print()
print(f"These two configurations differ in sequence length by "
      f"{len(ids1) - len(ids2)} tokens ({(1 - len(ids2)/len(ids1))*100:.1f}%)")

Configuration 1 (BPE + Discrete + Factored):
  Total tokens: 530
  Vocab size:   1024
  vals array:   None

Configuration 2 (BPE + Continuous + Fused):
  Total tokens: 374
  Vocab size:   1024
  vals array:   374

These two configurations differ in sequence length by 156 tokens (29.4%)

## Save & Load Round-Trip

In [33]:
import tempfile, os

with tempfile.TemporaryDirectory() as tmpdir:
    path = os.path.join(tmpdir, "demo_tokenizer")
    tok2.save(path)
    tok2_loaded = DBTokenizer.load(path)

    ids2_rt, vals2_rt = tok2_loaded.encode(df)
    assert ids2 == ids2_rt, "Token ID mismatch after round-trip!"
    assert len(vals2) == len(vals2_rt), "Vals length mismatch!"
    print("Save/load round-trip: PASSED ✓")

Saved tokenizer to /var/folders/7r/qkkh3v9151b193g38m3fslfw0000gn/T/tmpjrl8me06/demo_tokenizer.json
Loaded tokenizer from /var/folders/7r/qkkh3v9151b193g38m3fslfw0000gn/T/tmpjrl8me06/demo_tokenizer.json
Save/load round-trip: PASSED ✓

In [34]:
# now we will turn the token stream back into a dataframe and see how it compares to the original

df_decoded = tok2.decode_to_dataframe(ids2, vals2)
print("Decoded dataframe head:")
print(df_decoded.head(10))    
print("\nOriginal dataframe head:")
print(df.head(10))

Decoded dataframe head:
shape: (10, 5)
┌─────┬─────────────────────┬────────────┬─────────────────────────────┬───────────────┐
│ id  ┆ time                ┆ class      ┆ text_value                  ┆ numeric_value │
│ --- ┆ ---                 ┆ ---        ┆ ---                         ┆ ---           │
│ i64 ┆ datetime[μs]        ┆ str        ┆ str                         ┆ f64           │
╞═════╪═════════════════════╪════════════╪═════════════════════════════╪═══════════════╡
│ 0   ┆ 1970-01-01 00:00:00 ┆ lab        ┆ hemoglobin                  ┆ 13.2          │
│ 0   ┆ 1970-01-01 00:00:00 ┆ lab        ┆ glucose                     ┆ 98.0          │
│ 0   ┆ 1970-01-01 00:05:00 ┆ lab        ┆ creatinine                  ┆ 0.9           │
│ 0   ┆ 1970-01-01 00:05:00 ┆ vital      ┆ heart_rate                  ┆ 78.0          │
│ 0   ┆ 1970-01-01 00:05:00 ┆ vital      ┆ blood_pressure_systolic     ┆ 128.0         │
│ 0   ┆ 1970-01-01 00:05:00 ┆ vital      ┆ blood_pressure_diastolic    ┆ 82.0          │
│ 0   ┆ 1970-01-01 00:10:00 ┆ vital      ┆ spo2                        ┆ 97.0          │
│ 0   ┆ 1970-01-01 00:10:00 ┆ medication ┆ lisinopril, oral, daily, mg ┆ 10.0          │
│ 0   ┆ 1970-01-01 00:15:00 ┆ medication ┆ metformin, oral, BID, mg    ┆ 500.0         │
│ 0   ┆ 1970-01-01 00:15:00 ┆ flowsheet  ┆ o2_device: room_air         ┆ null          │
└─────┴─────────────────────┴────────────┴─────────────────────────────┴───────────────┘

Original dataframe head:
shape: (10, 5)
┌─────┬─────────────────────┬─────────────┬─────────────────────────────┬───────────────┐
│ id  ┆ time                ┆ class       ┆ text_value                  ┆ numeric_value │
│ --- ┆ ---                 ┆ ---         ┆ ---                         ┆ ---           │
│ i64 ┆ datetime[μs]        ┆ str         ┆ str                         ┆ f64           │
╞═════╪═════════════════════╪═════════════╪═════════════════════════════╪═══════════════╡
│ 1   ┆ 1958-03-15 00:00:00 ┆ demographic ┆ birth_date                  ┆ null          │
│ 1   ┆ 2024-01-02 08:00:00 ┆ lab         ┆ hemoglobin                  ┆ 13.2          │
│ 1   ┆ 2024-01-02 08:00:00 ┆ lab         ┆ glucose                     ┆ 98.0          │
│ 1   ┆ 2024-01-02 08:00:00 ┆ lab         ┆ creatinine                  ┆ 0.9           │
│ 1   ┆ 2024-01-02 08:05:00 ┆ vital       ┆ heart_rate                  ┆ 78.0          │
│ 1   ┆ 2024-01-02 08:05:00 ┆ vital       ┆ blood_pressure_systolic     ┆ 128.0         │
│ 1   ┆ 2024-01-02 08:05:00 ┆ vital       ┆ blood_pressure_diastolic    ┆ 82.0          │
│ 1   ┆ 2024-01-02 08:05:00 ┆ vital       ┆ spo2                        ┆ 97.0          │
│ 1   ┆ 2024-01-02 08:10:00 ┆ medication  ┆ lisinopril, oral, daily, mg ┆ 10.0          │
│ 1   ┆ 2024-01-02 08:10:00 ┆ medication  ┆ metformin, oral, BID, mg    ┆ 500.0         │
└─────┴─────────────────────┴─────────────┴─────────────────────────────┴───────────────┘

## Plain Concept vs. Split Concept vs. BPE Tokenization

The configurations above remain unchanged. This isolated example contrasts one-token concept values, prescribed per-class splitting, and learned BPE pieces. Medication values use the literal delimiter `", "` (comma followed by a space), while vital values use `"_"`.

In [35]:
# Select one representative row from each class so the contrast is easy to see.
split_examples = pl.concat([
    df.filter(pl.col("class") == "vital").head(1),
    df.filter(pl.col("class") == "medication").head(1),
]).sort(["id", "time", "class"])
split_examples.select(["class", "text_value", "numeric_value"])

shape: (2, 3)
┌────────────┬─────────────────────────────┬───────────────┐
│ class      ┆ text_value                  ┆ numeric_value │
│ ---        ┆ ---                         ┆ ---           │
│ str        ┆ str                         ┆ f64           │
╞════════════╪═════════════════════════════╪═══════════════╡
│ vital      ┆ heart_rate                  ┆ 78.0          │
│ medication ┆ lisinopril, oral, daily, mg ┆ 10.0          │
└────────────┴─────────────────────────────┴───────────────┘

In [36]:
plain_concept_tok = DBTokenizer(
    text_mode_default="concept",
    num_type="discrete",
    num_seq="factored",
)
split_concept_tok = DBTokenizer(
    text_mode_default="concept",
    concept_splitters={
        "medication": ", ",
        "vital": "_",
    },
    num_type="discrete",
    num_seq="factored",
)
bpe_tok = DBTokenizer(
    text_mode_default="bpe",
    num_type="discrete",
    num_seq="factored",
    final_vocab_size=510,
)

plain_concept_tok.train(split_examples)
split_concept_tok.train(split_examples)
bpe_tok.train(split_examples)

Extracting birth dates from data...
  No birth-date rows found
Resolving per-class text modes...
  2 concept classes, 0 BPE classes, 0 pair-level overrides
Training numeric transforms...
  2 numeric groups: 2 level, 0 bins, 0 scaling
Training time-delta transforms...
  scale '0' time-delta: bins (-)
Building vocabulary...
  Concept vocab size: 230
Training complete.
Extracting birth dates from data...
  No birth-date rows found
Resolving per-class text modes...
  2 concept classes, 0 BPE classes, 0 pair-level overrides
Training numeric transforms...
  2 numeric groups: 2 level, 0 bins, 0 scaling
Training time-delta transforms...
  scale '0' time-delta: bins (-)
Building vocabulary...
  Concept vocab size: 234
Training complete.
Extracting birth dates from data...
  No birth-date rows found
Resolving per-class text modes...
  0 concept classes, 2 BPE classes, 0 pair-level overrides
Training numeric transforms...
  2 numeric groups: 2 level, 0 bins, 0 scaling
Training time-delta transforms...
  scale '0' time-delta: bins (-)
Building vocabulary...
  BPE vocab size: 510 (228 special/concept, 282 BPE merges)
Training complete.

In [37]:
plain_debug = plain_concept_tok.encode_debug(split_examples)
split_debug = split_concept_tok.encode_debug(split_examples)
bpe_debug = bpe_tok.encode_debug(split_examples)

# replace double pipe with quote comma quote. no surrouting spaces on the tokens

# print original data rows
print(split_examples)

print("Demonstration of concept splitting using \"_\" for vitals and \", \" for meds as the splitters")

for row, plain_tokens, split_tokens, bpe_tokens in zip(
    split_examples.iter_rows(named=True),
    plain_debug["tokens"].to_list(),
    split_debug["tokens"].to_list(),
    bpe_debug["tokens"].to_list(),
):
    print(f"{row['class'].upper()}: {row['text_value']}")
    print("  plain concept:")
    print("   " + "\", \"".join(plain_tokens))
    print("  split concept:")
    print("   " + "\", \"".join(split_tokens))
    print("  BPE:")
    print("   " + "\", \"".join(bpe_tokens))
    print()

shape: (2, 5)
┌─────┬─────────────────────┬────────────┬─────────────────────────────┬───────────────┐
│ id  ┆ time                ┆ class      ┆ text_value                  ┆ numeric_value │
│ --- ┆ ---                 ┆ ---        ┆ ---                         ┆ ---           │
│ i64 ┆ datetime[μs]        ┆ str        ┆ str                         ┆ f64           │
╞═════╪═════════════════════╪════════════╪═════════════════════════════╪═══════════════╡
│ 1   ┆ 2024-01-02 08:05:00 ┆ vital      ┆ heart_rate                  ┆ 78.0          │
│ 1   ┆ 2024-01-02 08:10:00 ┆ medication ┆ lisinopril, oral, daily, mg ┆ 10.0          │
└─────┴─────────────────────┴────────────┴─────────────────────────────┴───────────────┘
Demonstration of concept splitting using "_" for vitals and ", " for meds as the splitters
VITAL: heart_rate
  plain concept:
   <|sos|>", "<|vital|>", "heart_rate", "<|L0|>
  split concept:
   <|sos|>", "<|vital|>", "heart", "rate", "<|L0|>
  BPE:
   <|sos|>", "<|vital|>", "heart", "_rate", "<|L0|>

MEDICATION: lisinopril, oral, daily, mg
  plain concept:
   <|delta_time_0|>", "<|Q0|>", "<|medication|>", "lisinopril, oral, daily, mg", "<|L0|>
  split concept:
   <|delta_time_0|>", "<|Q0|>", "<|medication|>", "lisinopril", "oral", "daily", "mg", "<|L0|>
  BPE:
   <|delta_time_0|>", "<|Q0|>", "<|medication|>", "lisinopril", ",", " oral", ",", " daily", ",", " mg", "<|L0|>

## MEDS-Style Hierarchical Codes

MEDS-style codes often carry an explicit hierarchy. Here each code uses a literal double backslash (`\\`) between levels, so the tokenizer can preserve those prescribed semantic boundaries instead of learning them from text.

In [39]:
from datetime import datetime, timedelta

meds_examples = pl.DataFrame(
    [
        {
            "id": 1,
            "time": datetime(2024, 1, 1),
            "class": "meds_code",
            "text_value": r"LAB\\LOINC\\2345-7",
            "numeric_value": None,
        },
        {
            "id": 1,
            "time": datetime(2024, 1, 1) + timedelta(minutes=1),
            "class": "meds_code",
            "text_value": r"DIAGNOSIS\\ICD10CM\\E11.9",
            "numeric_value": None,
        },
    ],
    schema_overrides={"numeric_value": pl.Float64},
)

meds_split_tok = DBTokenizer(
    text_mode_default="auto",
    concept_splitters={"meds_code": r"\\"},
    num_type="discrete",
    num_seq="factored",
)
meds_split_tok.train(meds_examples)
meds_debug = meds_split_tok.encode_debug(meds_examples)

for code, tokens in zip(
    meds_debug["text_value"].to_list(),
    meds_debug["tokens"].to_list(),
):
    pieces = [token for token in tokens if not token.startswith("<|")]
    print(f"MEDS code: {code!r}")
    print(f"  concept pieces: {pieces}")

meds_ids, meds_vals = meds_split_tok.encode(meds_examples)
meds_reconstructed = meds_split_tok.decode_to_dataframe(
    meds_ids, meds_vals, reference_time=datetime(2024, 1, 1)
)
assert meds_reconstructed["text_value"].to_list() == meds_examples["text_value"].to_list()
print("Exact MEDS code round-trip: PASSED")

Extracting birth dates from data...
  No birth-date rows found
Resolving per-class text modes...
  1 concept classes, 0 BPE classes, 0 pair-level overrides
Training numeric transforms...
  No numeric values found.
Training time-delta transforms...
  scale '0' time-delta: bins (-)
Building vocabulary...
  Concept vocab size: 233
Training complete.
MEDS code: 'LAB\\\\LOINC\\\\2345-7'
  concept pieces: ['LAB', 'LOINC', '2345-7']
MEDS code: 'DIAGNOSIS\\\\ICD10CM\\\\E11.9'
  concept pieces: ['DIAGNOSIS', 'ICD10CM', 'E11.9']
Exact MEDS code round-trip: PASSED

## End-to-end fitting on a patient split

`data/demo.csv` is included with this repository and is entirely synthetic.
The earlier sections inspect the full fixture. For this fitting example we split
by patient **before** training fresh tokenizers: one patient for training and
one for evaluation. The small fixture demonstrates the API only.
Install the examples' dependencies from this repository with
`python -m pip install -e ".[bpe,metrics]"` and run from the repository root.

Medication and flowsheet text are forced to BPE in this split example to encode
unseen evaluation strings. Concept-mode values require a known vocabulary.

In [40]:
patient_ids = sorted(df['id'].unique().to_list())
train_df = df.filter(pl.col("id") == patient_ids[0])
eval_df = df.filter(pl.col("id") == patient_ids[1])

## Fit a minimal causal model and evaluate bits per row

All data-loader definitions, model definitions, forward calls, and optimizer
steps are included below; no example helper module is imported.
The models use a small causal GRU and run on CPU. BPE changes the token vocabulary,
not the model interface. Both concept and BPE IDs enter an embedding layer.

- **Discrete:** the loader yields `(Xi, Yi)` int64 tensors of shape `[B, T]`.
  `Yi` contains the next token at each position. `model(Xi)` returns
  `(logits, loss)`; logits have shape `[B, T, V]`. Training passes `Yi` for
  categorical cross-entropy. There is no float input or regression head.
- **Continuous:** the loader yields `(Xi, Xv, Yi, Yv)`. IDs are int64;
  aligned values are float32, with NaN at positions without a float payload.
  `model(Xi, Xv, Yi, Yv)` returns `(logits, loc, scale, loss, token_loss,
  value_loss)` as required by the BPR helper. `loc` and positive `scale` are
  `[B, T]` Gaussian parameters in the tokenizer's transformed numeric space.
  The model consumes numeric values and their presence mask; value loss ignores
  NaN targets. Low-cardinality L-level measurements remain categorical.

Each batch contains one complete patient, so targets never cross patient boundaries
and numeric context is retained for BPR. No padding or window truncation is used.
Only four patients per split are used here to keep the fitting example small.
The tokenizer is fixed before evaluation. The short fit is a usage demonstration;
its scores are not a benchmark of predictive performance.

In [41]:
import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader
from dbtoken.metrics import bits_per_row

def vocabulary_size(tokenizer):
    """Include BPE IDs, which are not all listed in tokenizer.vocab."""
    return tokenizer.bpe.n_vocab if tokenizer.bpe is not None else max(tokenizer.vocab.values()) + 1

## Discrete: train tokenizer → save tokens → fit model → evaluate

In [43]:
model_tok_discrete = DBTokenizer(text_mode_default="auto", text_mode_threshold=4,
    text_mode_overrides={"medication": "bpe", "flowsheet": "bpe"},
    num_type="discrete", num_seq="factored", n_bins=5, final_vocab_size=1024)
model_tok_discrete.train(train_df)

Extracting birth dates from data...
  Found birth dates for 1 patients
Resolving per-class text modes...
  4 concept classes, 2 BPE classes, 0 pair-level overrides
Training numeric transforms...
  11 numeric groups: 11 level, 0 bins, 0 scaling
Training time-delta transforms...
  scale '0' time-delta: bins (-)
Building vocabulary...
  BPE vocab size: 586 (236 special/concept, 350 BPE merges)
Training complete.

## Files on disk and save/load verification

Each representation has its own `artifacts/<mode>/` directory. `tokenizer.json`
contains the constructor settings, resolved text modes, vocabulary, numeric bin
edges/levels or fitted scaling parameters, temporal parameters, and demographic
metadata. BPE configurations also write `tokenizer.bpe` containing the serialized
BPE encoding; retain it alongside the JSON and load artifacts from trusted sources.
These are tokenizer artifacts, not model weights. Never reuse a model with a
differently trained vocabulary.

`train.npz` and `eval.npz` store complete encoded streams: `ids` is int64;
continuous files additionally contain aligned float32 `vals`. Discrete files
omit `vals`. Read with `np.load(..., allow_pickle=False)`. These streams include
patient boundary tokens. The model loaders below encode each patient separately
to avoid predicting across patients and to retain full numeric context.

In [44]:
from pathlib import Path
artifact_dir = Path("artifacts/discrete_factored")
artifact_dir.mkdir(parents=True, exist_ok=True)
model_tok_discrete.save(str(artifact_dir / "tokenizer"))
for split, frame in [("train", train_df), ("eval", eval_df)]:
    stream_ids, stream_vals = model_tok_discrete.encode(frame)
    arrays = {"ids": np.asarray(stream_ids, dtype=np.int64)}
    if stream_vals is not None:
        arrays["vals"] = np.asarray(stream_vals, dtype=np.float32)
    np.savez_compressed(artifact_dir / f"{split}.npz", **arrays)

restored = DBTokenizer.load(str(artifact_dir / "tokenizer"))
original_ids, original_vals = model_tok_discrete.encode(eval_df)
restored_ids, restored_vals = restored.encode(eval_df)
assert original_ids == restored_ids
if original_vals is not None:
    np.testing.assert_allclose(original_vals, restored_vals, equal_nan=True)
else:
    assert restored_vals is None
with np.load(artifact_dir / "eval.npz", allow_pickle=False) as saved:
    print("Saved arrays:", {key: (saved[key].shape, str(saved[key].dtype)) for key in saved.files})
print("Save/load equality verified. Files:", [p.name for p in sorted(artifact_dir.iterdir())])

Saved tokenizer to artifacts/discrete_factored/tokenizer.json
Loaded tokenizer from artifacts/discrete_factored/tokenizer.json
Saved arrays: {'ids': ((291,), 'int64')}
Save/load equality verified. Files: ['eval.npz', 'tokenizer.bpe', 'tokenizer.json', 'train.npz']

### Discrete data loader and model

The loader returns `(Xi, Yi)`. IDs are int64. `Yi` is the next-token target;
the model predicts categorical logits with shape `[B,T,V]`.

In [45]:
def make_discrete_loader(tokenizer, frame, max_patients=4):
    """Separate complete patients; batches contain int64 (Xi, Yi), [1,T]."""
    if tokenizer.num_type != "discrete":
        raise ValueError("Use a discrete tokenizer with this loader")
    samples = []
    for patient in frame["id"].unique().sort().head(max_patients):
        ids, vals = tokenizer.encode(frame.filter(pl.col("id") == patient))
        assert vals is None
        if len(ids) < 2:
            continue
        ids = torch.tensor(ids, dtype=torch.long)
        # Predict the next token without crossing a patient boundary.
        samples.append((ids[:-1], ids[1:]))
    if not samples:
        raise ValueError("No patient sequences with at least two tokens")
    # Batch size 1 supports different sequence lengths without padding.
    return DataLoader(samples, batch_size=1, shuffle=False)

In [46]:
class DiscreteModel(nn.Module):
    """Embedding → causal GRU → categorical next-token logits [B,T,V]."""
    def __init__(self, vocab_size, width=24):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, width)
        self.rnn = nn.GRU(width, width, batch_first=True)
        self.head = nn.Linear(width, vocab_size)

    def forward(self, xi, targets=None):
        hidden, _ = self.rnn(self.embedding(xi))
        logits = self.head(hidden)
        loss = None if targets is None else F.cross_entropy(
            logits.reshape(-1, logits.size(-1)), targets.reshape(-1))
        return logits, loss

In [47]:
torch.manual_seed(7)
discrete_train_loader = make_discrete_loader(model_tok_discrete, train_df, max_patients=4)
discrete_eval_loader = make_discrete_loader(model_tok_discrete, eval_df, max_patients=4)
discrete_model = DiscreteModel(vocabulary_size(model_tok_discrete))
print("Batch tensor shapes:", [tuple(t.shape) for t in next(iter(discrete_train_loader))])
Xi, Yi = next(iter(discrete_train_loader))
print("Xi (input IDs):", Xi[0, :8])
print("Yi (next IDs): ", Yi[0, :8])
logits, loss = discrete_model(Xi, Yi)
print("Next-token logits:", tuple(logits.shape), "initial loss:", loss.item())

Batch tensor shapes: [(1, 276), (1, 276)]
Xi (input IDs): tensor([350, 514, 574, 583, 365, 574, 577, 361])
Yi (next IDs):  tensor([514, 574, 583, 365, 574, 577, 361, 574])
Next-token logits: (1, 276, 586) initial loss: 6.374086380004883

### Fit the discrete model

In [50]:
# Fit this model using its representation-specific input/target tensors.
optimizer = torch.optim.Adam(discrete_model.parameters(), lr=0.003)
discrete_model.train()
for epoch in range(50):
    total_loss = 0.0
    for batch in discrete_train_loader:
        optimizer.zero_grad()
        Xi, Yi = batch
        _, loss = discrete_model(Xi, Yi)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch + 1} mean loss: {total_loss / len(discrete_train_loader):.4f}")

Epoch 1 mean loss: 5.6149
Epoch 2 mean loss: 5.5248
Epoch 3 mean loss: 5.4300
Epoch 4 mean loss: 5.3307
Epoch 5 mean loss: 5.2275
Epoch 6 mean loss: 5.1211
Epoch 7 mean loss: 5.0123
Epoch 8 mean loss: 4.9021
Epoch 9 mean loss: 4.7918
Epoch 10 mean loss: 4.6828
Epoch 11 mean loss: 4.5763
Epoch 12 mean loss: 4.4739
Epoch 13 mean loss: 4.3769
Epoch 14 mean loss: 4.2866
Epoch 15 mean loss: 4.2036
Epoch 16 mean loss: 4.1280
Epoch 17 mean loss: 4.0593
Epoch 18 mean loss: 3.9969
Epoch 19 mean loss: 3.9398
Epoch 20 mean loss: 3.8871
Epoch 21 mean loss: 3.8379
Epoch 22 mean loss: 3.7916
Epoch 23 mean loss: 3.7477
Epoch 24 mean loss: 3.7060
Epoch 25 mean loss: 3.6661
Epoch 26 mean loss: 3.6281
Epoch 27 mean loss: 3.5917
Epoch 28 mean loss: 3.5569
Epoch 29 mean loss: 3.5237
Epoch 30 mean loss: 3.4919
Epoch 31 mean loss: 3.4614
Epoch 32 mean loss: 3.4322
Epoch 33 mean loss: 3.4042
Epoch 34 mean loss: 3.3772
Epoch 35 mean loss: 3.3511
Epoch 36 mean loss: 3.3259
Epoch 37 mean loss: 3.3013
Epoch 38 mean loss: 3.2773
Epoch 39 mean loss: 3.2538
Epoch 40 mean loss: 3.2306
Epoch 41 mean loss: 3.2075
Epoch 42 mean loss: 3.1846
Epoch 43 mean loss: 3.1617
Epoch 44 mean loss: 3.1387
Epoch 45 mean loss: 3.1158
Epoch 46 mean loss: 3.0928
Epoch 47 mean loss: 3.0697
Epoch 48 mean loss: 3.0466
Epoch 49 mean loss: 3.0234
Epoch 50 mean loss: 3.0001

### Evaluate the discrete model with BPR

In [51]:
# Evaluate the fixed tokenizer and fitted model on held-out histories.
discrete_scores = bits_per_row(
    discrete_model, model_tok_discrete, discrete_eval_loader,
    model_type="discrete", tail_mode="width",
)
print("Discrete BPR results:")
for name, value in discrete_scores.items():
    print(f"  {name}: {value}")
assert discrete_scores["n_rows"] > 0

Discrete BPR results:
  bpr: 41.88427868168336
  bpr_raw: 37.369078136980534
  eos_bpr: 0.14285056789716086
  time_bpr: 7.041738479641893
  milestone_bpr: 0.0
  age_bpr: 0.2105849583943685
  class_bpr: 4.040720557173093
  text_bpr: 26.847377610703308
  numeric_bpr: 0.0
  level_bpr: 3.601006507873535
  fused_bpr: 0.0
  n_rows: 48
  tokens_per_row: 6.041666666666667
  tail_mode: width

## Continuous: train tokenizer → save tokens → fit model → evaluate

In [52]:
model_tok_continuous = DBTokenizer(text_mode_default="auto", text_mode_threshold=4,
    text_mode_overrides={"medication": "bpe", "flowsheet": "bpe"},
    num_type="continuous", num_seq="fused", n_bins=5, final_vocab_size=1024)
model_tok_continuous.train(train_df)

Extracting birth dates from data...
  Found birth dates for 1 patients
Resolving per-class text modes...
  4 concept classes, 2 BPE classes, 0 pair-level overrides
Training numeric transforms...
  11 numeric groups: 11 level, 0 bins, 0 scaling
Training time-delta transforms...
  scale '0' time-delta: scaling (lognormal)
Building vocabulary...
  BPE vocab size: 623 (273 special/concept, 350 BPE merges)
Training complete.

/Users/giacomomarino/Projects/dbtoken/dbtoken/tokenizer.py:657: UserWarning: num_seq='fused' but 2 classes use BPE text mode (e.g. ['medication', 'flowsheet']). These will silently use factored numeric placement unless overridden at pair level.
  warnings.warn(
/Users/giacomomarino/Projects/dbtoken/dbtoken/tokenizer.py:706: UserWarning: Distribution auto-detect failed: unable to find column "count"; valid columns: []. Falling back to normal.
  warnings.warn(

In [53]:
from pathlib import Path
artifact_dir = Path("artifacts/continuous_fused")
artifact_dir.mkdir(parents=True, exist_ok=True)
model_tok_continuous.save(str(artifact_dir / "tokenizer"))
for split, frame in [("train", train_df), ("eval", eval_df)]:
    stream_ids, stream_vals = model_tok_continuous.encode(frame)
    arrays = {"ids": np.asarray(stream_ids, dtype=np.int64)}
    if stream_vals is not None:
        arrays["vals"] = np.asarray(stream_vals, dtype=np.float32)
    np.savez_compressed(artifact_dir / f"{split}.npz", **arrays)

restored = DBTokenizer.load(str(artifact_dir / "tokenizer"))
original_ids, original_vals = model_tok_continuous.encode(eval_df)
restored_ids, restored_vals = restored.encode(eval_df)
assert original_ids == restored_ids
if original_vals is not None:
    np.testing.assert_allclose(original_vals, restored_vals, equal_nan=True)
else:
    assert restored_vals is None
with np.load(artifact_dir / "eval.npz", allow_pickle=False) as saved:
    print("Saved arrays:", {key: (saved[key].shape, str(saved[key].dtype)) for key in saved.files})
print("Save/load equality verified. Files:", [p.name for p in sorted(artifact_dir.iterdir())])

Saved tokenizer to artifacts/continuous_fused/tokenizer.json
Loaded tokenizer from artifacts/continuous_fused/tokenizer.json
Saved arrays: {'ids': ((244,), 'int64'), 'vals': ((244,), 'float32')}
Save/load equality verified. Files: ['eval.npz', 'tokenizer.bpe', 'tokenizer.json', 'train.npz']

### Continuous data loader and model

The loader returns `(Xi, Xv, Yi, Yv)`. IDs are int64 and values are float32.
Values stay aligned when shifted into inputs and targets. NaN marks positions
without a float. The model consumes values and missingness, and predicts
categorical logits plus Gaussian location and positive scale `[B,T]`.

In [54]:
def make_continuous_loader(tokenizer, frame, max_patients=4):
    """Batches contain (Xi, Xv, Yi, Yv), all [1,T]; NaN means no float."""
    if tokenizer.num_type != "continuous":
        raise ValueError("Use a continuous tokenizer with this loader")
    samples = []
    for patient in frame["id"].unique().sort().head(max_patients):
        ids, vals = tokenizer.encode(frame.filter(pl.col("id") == patient))
        assert vals is not None and len(ids) == len(vals)
        if len(ids) < 2:
            continue
        ids = torch.tensor(ids, dtype=torch.long)
        vals = torch.tensor(vals, dtype=torch.float32)
        # Shift IDs and their aligned floats together. Keep NaN payloads:
        # the model handles missing inputs and masks missing value targets.
        samples.append((ids[:-1], vals[:-1], ids[1:], vals[1:]))
    if not samples:
        raise ValueError("No patient sequences with at least two tokens")
    return DataLoader(samples, batch_size=1, shuffle=False)

In [57]:
class ContinuousModel(nn.Module):
    """Token + value + missingness inputs; categorical and Gaussian outputs.

    Match bits_per_row's six-result forward interface. Gaussian loc/scale
    and value targets are [B,T]; scale must be positive. NaN targets mark
    positions with no continuous payload and are excluded from value loss.
    Discrete L-level tokens remain categorical even in continuous mode.
    """
    def __init__(self, vocab_size, width=24):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, width)
        self.value_embedding = nn.Linear(2, width)
        self.rnn = nn.GRU(width, width, batch_first=True)
        self.token_head = nn.Linear(width, vocab_size)
        self.value_head = nn.Linear(width, 2)

    def forward(self, xi, xv, yi=None, yv=None):
        present = ~torch.isnan(xv)
        features = torch.stack((torch.nan_to_num(xv), present.float()), dim=-1)
        hidden, _ = self.rnn(self.embedding(xi) + self.value_embedding(features))
        logits = self.token_head(hidden)
        loc, raw_scale = self.value_head(hidden).unbind(-1)
        scale = F.softplus(raw_scale) + 1e-4
        loss = token_loss = value_loss = None
        if yi is not None:
            token_loss = F.cross_entropy(logits.reshape(-1, logits.size(-1)), yi.reshape(-1))
            mask = ~torch.isnan(yv)
            # Index first: a NaN must never enter the Gaussian likelihood.
            value_loss = (-torch.distributions.Normal(loc[mask], scale[mask])
                          .log_prob(yv[mask]).mean()) if mask.any() else loc.sum() * 0
            loss = token_loss + value_loss
        return logits, loc, scale, loss, token_loss, value_loss

In [58]:
torch.manual_seed(7)
continuous_train_loader = make_continuous_loader(model_tok_continuous, train_df, max_patients=4)
continuous_eval_loader = make_continuous_loader(model_tok_continuous, eval_df, max_patients=4)
continuous_model = ContinuousModel(vocabulary_size(model_tok_continuous))
print("Batch tensor shapes:", [tuple(t.shape) for t in next(iter(continuous_train_loader))])
Xi, Xv, Yi, Yv = next(iter(continuous_train_loader))
print("Xi (input IDs):", Xi[0, :8])
print("Xv (input values):", Xv[0, :8])
print("Yi (next IDs):", Yi[0, :8])
print("Yv (next values):", Yv[0, :8])
logits, loc, scale, loss, token_loss, value_loss = continuous_model(Xi, Xv, Yi, Yv)
print("Next-token logits:", tuple(logits.shape), "initial loss:", loss.item())

Batch tensor shapes: [(1, 219), (1, 219), (1, 219), (1, 219)]
Xi (input IDs): tensor([350, 514, 575, 590, 575, 596, 575, 607])
Xv (input values): tensor([nan, nan, nan, nan, nan, nan, nan, nan])
Yi (next IDs): tensor([514, 575, 590, 575, 596, 575, 607, 353])
Yv (next values): tensor([    nan,     nan,     nan,     nan,     nan,     nan,     nan, -0.9254])
Next-token logits: (1, 219, 623) initial loss: 8.055756568908691

### Fit the continuous model

In [61]:
# Fit this model using its representation-specific input/target tensors.
optimizer = torch.optim.Adam(continuous_model.parameters(), lr=0.003)
continuous_model.train()
for epoch in range(50):
    total_loss = 0.0
    for batch in continuous_train_loader:
        optimizer.zero_grad()
        Xi, Xv, Yi, Yv = batch
        _, _, _, loss, _, _ = continuous_model(Xi, Xv, Yi, Yv)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch + 1} mean loss: {total_loss / len(continuous_train_loader):.4f}")

Epoch 1 mean loss: 7.7598
Epoch 2 mean loss: 7.6418
Epoch 3 mean loss: 7.5369
Epoch 4 mean loss: 7.4402
Epoch 5 mean loss: 7.3473
Epoch 6 mean loss: 7.2550
Epoch 7 mean loss: 7.1610
Epoch 8 mean loss: 7.0639
Epoch 9 mean loss: 6.9629
Epoch 10 mean loss: 6.8579
Epoch 11 mean loss: 6.7486
Epoch 12 mean loss: 6.6352
Epoch 13 mean loss: 6.5177
Epoch 14 mean loss: 6.3961
Epoch 15 mean loss: 6.2702
Epoch 16 mean loss: 6.1397
Epoch 17 mean loss: 6.0044
Epoch 18 mean loss: 5.8642
Epoch 19 mean loss: 5.7196
Epoch 20 mean loss: 5.5718
Epoch 21 mean loss: 5.4219
Epoch 22 mean loss: 5.2697
Epoch 23 mean loss: 5.1149
Epoch 24 mean loss: 4.9590
Epoch 25 mean loss: 4.8034
Epoch 26 mean loss: 4.6463
Epoch 27 mean loss: 4.4872
Epoch 28 mean loss: 4.3298
Epoch 29 mean loss: 4.1733
Epoch 30 mean loss: 4.0197
Epoch 31 mean loss: 3.8667
Epoch 32 mean loss: 3.7145
Epoch 33 mean loss: 3.5585
Epoch 34 mean loss: 3.4016
Epoch 35 mean loss: 3.2482
Epoch 36 mean loss: 3.1110
Epoch 37 mean loss: 2.9953
Epoch 38 mean loss: 2.8471
Epoch 39 mean loss: 2.6832
Epoch 40 mean loss: 2.5794
Epoch 41 mean loss: 2.4986
Epoch 42 mean loss: 2.3473
Epoch 43 mean loss: 2.1825
Epoch 44 mean loss: 2.1277
Epoch 45 mean loss: 2.1346
Epoch 46 mean loss: 1.9481
Epoch 47 mean loss: 1.7308
Epoch 48 mean loss: 1.7378
Epoch 49 mean loss: 1.8554
Epoch 50 mean loss: 1.6722

### Evaluate the continuous model with BPR

In [62]:
# Evaluate the fixed tokenizer and fitted model on held-out histories.
continuous_scores = bits_per_row(
    continuous_model, model_tok_continuous, continuous_eval_loader,
    model_type="continuous", tail_mode="width",
)
print("Continuous BPR results:")
for name, value in continuous_scores.items():
    print(f"  {name}: {value}")
assert continuous_scores["n_rows"] > 0

Continuous BPR results:
  bpr: 49.38511591681544
  bpr_raw: 44.91152612864971
  eos_bpr: 0.16125225027402243
  time_bpr: 16.170509870138805
  milestone_bpr: 0.0
  age_bpr: 0.21676085392634073
  class_bpr: 4.295386642217636
  text_bpr: 23.620897864302
  numeric_bpr: 0.0
  level_bpr: 0.3219572852055232
  fused_bpr: 4.598351150751114
  n_rows: 48
  tokens_per_row: 5.0625
  tail_mode: width

The returned BPR dictionaries are printed in full above. `bpr` is the
sum of density-adjusted bits divided by the number of represented data rows;
`bpr_raw` omits the density adjustment. `class_bpr`, `text_bpr`, `numeric_bpr`,
`level_bpr`, `fused_bpr`, `time_bpr`, `milestone_bpr`, `age_bpr`, and `eos_bpr`
show the contributions. `n_rows`, `tokens_per_row`, and `tail_mode` describe
what was scored. Birth-date metadata rows do not count as clinical rows.
Lower BPR indicates better likelihood on the same evaluation rows. Comparisons
require identical source rows, units, splits, and tail conventions. Density-based
scores may be negative. `tail_mode="width"` borrows neighboring widths for open
edge bins; `"censored"` instead scores tail events as probability mass.